### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by zocom-david-lundholm** [nitipon-apaisri/Library-of-Beers#2]
Bra jobbat!

* Du vill enbart ha en JS-fil, samma sak för CSS
* Det blir en hel del `<div>`-element när man måste följa ett CSS-bibliotek. Försök ändå att använda så mkt semantiska element som möjligt.

**Comment by nitipon-apaisri** [comment]
Har fixat JS-fill och CSS men om HTML, ska försöka för den - i alla fall.
